# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-03 18:54
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_Empleado', models.CharField(choices=[('1', 'Administrador'), ('2', 'Tecnico'), ('3', 'Cobranza')], max_length=2, verbose_name='Tipo de Empleado')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha')),
                ('Actividades', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('Descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('Beneficios', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('Estatus', models.BooleanField(default=True, verbose_name='1')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaInscripcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inscripcion')),
                ('NombreCliente', models.CharField(max_length=25)),
                ('ApellidoPaterno', models.CharField(max_length=15, verbose_name='Apellido Paterno')),
                ('ApellidoMaterno', models.CharField(max_length=15, verbose_name='Apellido Materno')),
                ('Direccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Direcci\xf3n')),
                ('Municipio', models.CharField(max_length=35)),
                ('NumeroTelefono', models.CharField(default='000-00-0-00-00', max_length=14, verbose_name='N\xfamero Telef\xf3nico')),
                ('DiaPago', models.IntegerField(verbose_name='Dia de Pago')),
                ('Estatus', models.BooleanField(default=True, verbose_name='1')),
            ],
        ),
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.FloatField(verbose_name='Cantidad')),
                ('Descripcion', models.CharField(max_length=30, verbose_name='Descripcion')),
                ('Estatus', models.BooleanField(default=True, verbose_name='1')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha ')),
                ('Descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('Costo', models.FloatField(verbose_name='Costo')),
                ('Estatus', models.BooleanField(default=True, verbose_name='1')),
                ('NombreCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Cliente2')),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaInicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('FechaFin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('Descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('Costo', models.FloatField(verbose_name='Costo')),
                ('Estatus', models.BooleanField(default=True, verbose_name='1')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.CharField(max_length=25)),
                ('Placa', models.CharField(max_length=10, verbose_name='Placa')),
                ('Marca', models.CharField(max_length=10, verbose_name='Marca')),
                ('Modelo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Modelo')),
                ('Color', models.CharField(max_length=10)),
                ('Estatus', models.BooleanField(default=True, verbose_name='1')),
            ],
        ),
        migrations.CreateModel(
            name='usuarioWiver',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Nombre', models.CharField(max_length=25)),
                ('ApellidoPaterno', models.CharField(max_length=15, verbose_name='Apellido Paterno')),
                ('ApellidoMaterno', models.CharField(max_length=15, verbose_name='Apellido Materno')),
                ('NumeroTelefono', models.CharField(default='000-00-0-00-00', max_length=14, verbose_name='N\xfamero Telef\xf3nico')),
                ('Direccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Direcci\xf3n')),
                ('Municipio', models.CharField(max_length=35)),
                ('Estatus', models.BooleanField(default=True, verbose_name='1')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('web.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='taller',
            name='Placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Unidad'),
        ),
        migrations.AddField(
            model_name='combustible',
            name='Placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Unidad'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='Nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usuarioWiver'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='Nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usuarioWiver'),
        ),
        migrations.AddField(
            model_name='combustible',
            name='Nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usuarioWiver'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='Nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usuarioWiver'),
        ),
    ]
