# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-03 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='Fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cliente2',
            name='FechaInscripcion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inscripcion'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='Fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha '),
        ),
        migrations.AlterField(
            model_name='taller',
            name='FechaFin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='FechaInicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
    ]
